[WIP] Improve doc
CMTA/CMTAT pull request #38
Opened 2022-09-22 07:20 UTC by rya-sge

Improve project documentation by adding diagrams, usage (installation, toolchain)

2022-10-04 12:19 UTC, rya-sge commented
Finish

2022-10-11 06:56 UTC, veorq requested changes
As discussed on Slack

2022-10-12 07:26 UTC, skrafft approved these changes

2022-11-04 15:35 UTC, rya-sge commented
The changes were included in the pull request #84

2022-11-04 15:35 UTC, closed without merging