Improve rule engine clean
CMTA/CMTAT pull request #74
Opened 2022-10-31 16:11 UTC by rya-sge

**CVF**

- CVF-66 : fixed with the commit [0a11ee5](https://github.com/CMTA/CMTAT/commit/0a11ee5b43c78ed540e443cf41ea3c27067e31a2)

- CVF-67 : not fixed, I do not think it is necessary to fix this CVF, it is more clear to separate IRuleEngine and IRule

Only the add function are added because remove functions need more reflexion and changes.

- CVF-69  fixed with the commit [a4e983131](https://github.com/CMTA/CMTAT/commit/a4e983131297dcd58a7eba3b7172b4d211406ed9)

Decision : create an interface IERC1404, whose inherits IRule and IRuleEngine

- CVF-70 fixed  with the commit [0a11ee5](https://github.com/CMTA/CMTAT/commit/0a11ee5b43c78ed540e443cf41ea3c27067e31a2)

- CVF-72 fixed in commit

2022-11-02 16:41 UTC, skrafft requested changes

2022-11-02 16:41 UTC, skrafft commented on contracts/interfaces/IERC1404.sol
> +    function isTransferValid(
EIP1404 (https://medium.com/erc1404/erc-1404-simple-restricted-token-standard-f71290a48faa) does not contain isTransferValid, I think we should move this function outside IERC1404.sol

2022-11-03 10:08 UTC, rya-sge commented
More improvements are possible, see [issues/82](https://github.com/CMTA/CMTAT/issues/82)

2022-11-03 10:33 UTC, rya-sge commented
List of changes : creation of an intermediary interface called IERC1404Wrapper.

2022-11-04 07:06 UTC, skrafft approved these changes

2022-11-04 08:02 UTC, merged